USE QLDT2
GO

ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_GIAOVIEN_PHAI
CHECK (PHAI IN (N'Nam', N'Nữ'))

INSERT INTO GIAOVIEN (MAGV, PHAI)
VALUES ('069', N'Na')

ALTER TABLE GIAOVIEN
DROP CONSTRAINT CK_GIAOVIEN_PHAI


-- CREATE RULE RULE_PHAI
-- AS
--     @PHAI IN (N'Nam', N'Nữ')
-- GO

-- EXEC SP_BINDRULE 'RULE_PHAI', 'GIAOVIEN.PHAI'

-- EXEC sp_unbindrule 'GIAOVIEN.PHAI'
-- GO

-- DROP RULE RULE_PHAI
-- GO

-- The project title must be unique. (Tên đề tài phải duy nhất)
CREATE TRIGGER 