USE QLDT2
GO

-- Q1. RETRIEVE THE FULL NAMES AND SALARIES OF FEMALE TEACHERS
SELECT G.HOTEN, G.LUONG
FROM GIAOVIEN G
WHERE G.PHAI = N'Nữ'

-- Q2. RETRIEVE THE FULL NAMES OF TEACHERS AND THEIR SALARIES AFTER A 10% INCREASE
SELECT G.HOTEN, G.LUONG * 1.1 AS 'LUONG DA TANG 10%'
FROM GIAOVIEN G

-- Q3. RETRIEVE THE IDs OF TEACHERS WHOSE NAMES START WITH "Nguyễn" AND WHOSE SALARIES ARE ABOVE $2000, OR WHO ARE DEPARTMENT HEADS APPOINTED AFTER 1995
SELECT DISTINCT G.MAGV
FROM GIAOVIEN G, BOMON B
WHERE ((G.HOTEN LIKE N'Nguyễn%') AND (G.LUONG > 2000)) OR (G.MAGV = B.TRUONGBM AND YEAR(B.NGAYNHANCHUC) > 1995)

-- Q4. RETRIVE THE NAMES OF TEACHERS IN THE FACULTY IF INFORMATION TECHNOLOGY
SELECT G.HOTEN
FROM GIAOVIEN G, BOMON B
WHERE G.MABM = B.MABM AND B.TENBM = N'Công nghệ thông tin'

-- Q5. RETRIEVE INFORMATION ABOUT DEPARTMENTS ALONG WITH THE INFORMATION ABOUT THE TEACHERS WHO SERVE AS DEPARTMENT HEADS
SELECT B.*, G.HOTEN AS 'TRUONGBM'
FROM GIAOVIEN G, BOMON B
WHERE G.MAGV = B.TRUONGBM

-- Q6. FOR EACH TEACHER, RETRIEVE INFORMATION ABOUT THE DEPARTMENT IN WHICH THEY WORK
SELECT G.*, B.TENBM
FROM GIAOVIEN G, BOMON B
WHERE G.MABM = B.MABM

-- Q7. RETRIEVE THE PROJECT NAMES AND THE TEACHERS WHO ARE IN CHARGE OF THOSE PROJECTS
SELECT D.TENDT, G.HOTEN
FROM DETAI D, GIAOVIEN G, THAMGIADT TG
WHERE D.MADT = TG.MADT AND TG.MAGV = G.MAGV

-- Q8. FOR EACH FACULTY, RETRIEVE INFORMATION ABOUT THE HEAD OF THE FACULTY
SELECT B.TENBM, G.*
FROM BOMON B, GIAOVIEN G
WHERE B.TRUONGBM = G.MAGV

-- Q9. RETRIEVE TEACHERS FROM THE "Vi sinh" DEPARTMENT WHO PARTICIPATE IN PROJECTS 006
SELECT G.*
FROM GIAOVIEN G, BOMON B, THAMGIADT TG
WHERE G.MABM = B.MABM AND B.TENBM = N'Vi sinh' AND G.MAGV = TG.MAGV AND TG.MADT = '006'

-- Q10. FOR PROJECTS MANAGED AT THE "Thành phố" LEVEL, RETRIEVE THE PROJECT ID, THE TOPIC TO WHICH THE PROJECT BELONGS, AND THE FULL NAME, DOB, AND ADDRESS OF THE PROJECT LEADER
SELECT D.MADT, CD.TENCD, G.*
FROM DETAI D, CHUDE CD, GIAOVIEN G
WHERE D.CAPQL = N'Thành phố' AND D.MACD = CD.MACD AND G.MAGV = D.GVCNDT

-- Q11. RETRIEVE THE FULL NAMES OF TEACHERS WHO ARE DIRECTLY SUPERVISED BY "Nguyễn Thanh Tùng"
SELECT G.HOTEN
FROM GIAOVIEN G, GIAOVIEN GV
WHERE G.GVQLCM = GV.MAGV AND GV.HOTEN = N'Nguyễn Thanh Tùng'

-- Q12. RETRIEVE THE NAME OF THE TEACHER WHO IS THE HEAD OF THE "Hệ thống thông tin" DEPARTMENT
SELECT G.HOTEN
FROM GIAOVIEN G, BOMON B
WHERE G.MAGV = B.TRUONGBM AND B.TENBM = N'Hệ thống thông tin'

-- Q13. RETRIEVE THE NAMES OF PROJECT LEADERS FOR PROJHECTS UNDER THE "Quản lý giáo dục" TOPIC
SELECT G.HOTEN
FROM GIAOVIEN G, DETAI D, CHUDE CD
WHERE G.MAGV = D.GVCNDT AND D.MACD = CD.MACD AND CD.TENCD = N'Quản lý giáo dục'

-- Q14. RETRIEVE THE NAMES OF TASKS IF THE PROJECT "HTTT quản lý các trường ĐH" THAT STARTED IN MARCH 2008
SELECT CV.TENCV
FROM CONGVIEC CV, DETAI D
WHERE CV.MADT = D.MADT AND D.TENDT = N'HTTT quản lý các trường ĐH' AND YEAR(D.NGAYBD) = 2008 AND MONTH(D.NGAYBD) = 3

-- Q15. RETRIEVE THE TEACHER'S NAME AND THE NAME OF THEIR ACADEMIC SUPERVISOR
SELECT G.HOTEN, GV.HOTEN AS 'SUPERVISOR_NAME'
FROM GIAOVIEN G, GIAOVIEN GV
WHERE G.GVQLCM = GV.MAGV

-- Q16. RETRIEVE TASKS THAT STARTED BETWEEN JAN 1, 2007 AND AUG 1, 2007.
SELECT CV.*
FROM CONGVIEC CV
WHERE CV.NGAYBD BETWEEN '2007-01-01' AND '2007-08-01'

-- Q17. RETRIEVE THE FULL NAMES OF TEACHERS WHO WORK IN THE SAME DEPARTMENT AS THE TEACHER "Trần Trà Hương"
SELECT G1.HOTEN
FROM GIAOVIEN G1, GIAOVIEN G2
WHERE G1.MABM = G2.MABM AND G2.HOTEN = N'Trần Trà Hương'

-- Q18. RETRIEVE TEACHERS WHO ARE BOTH DEPARTMENT HEADS AND PROJECT LEADERS.
SELECT G.*
FROM GIAOVIEN G, BOMON B, DETAI D
WHERE G.MAGV = B.TRUONGBM AND G.MAGV = D.GVCNDT

-- Q19. RETRIEVE THE NAMES OF TEACHERS WHO ARE BOTH FACULTY HEADS AND DEPARTMENT HEADS
SELECT G.HOTEN
FROM GIAOVIEN G, BOMON B, KHOA K
WHERE G.MAGV = B.TRUONGBM AND G.MAGV = K.TRUONGKHOA

-- Q20. RETRIEVE THE NAMES OF DEPARTMENT HEADS WHO ARE ALSO PROJECT LEADERS
SELECT G.HOTEN
FROM BOMON B, GIAOVIEN G, DETAI D
WHERE B.TRUONGBM = G.MAGV AND G.MAGV = D.GVCNDT

-- Q21. RETRIEVE THE IDS OF FACULTY HEADS WHO ARE PROJECT LEADERS
SELECT G.MAGV
FROM GIAOVIEN G, KHOA K, DETAI D
WHERE G.MAGV = K.TRUONGKHOA AND G.MAGV = D.GVCNDT

-- Q22. RETRIEVE THE IDS OF TEACHERS WHO BELONG TO THE "HTTT" DEPARTMENT OR WHO PARTICIPATE IN PROJECT "001"
SELECT DISTINCT G.MAGV
FROM GIAOVIEN G, BOMON B, THAMGIADT TG
WHERE (G.MABM = B.MABM AND B.TENBM = 'HTTT') OR G.MAGV = TG.MAGV

-- Q23. RETRIEVE THE IDS OF TEACHERS WHO WORK ON THE SAME DEPARTMENT AS TEACHER 002
SELECT G.MAGV
FROM GIAOVIEN G, GIAOVIEN G2
WHERE G.MABM = G2.MABM AND G2.MAGV = '002'

-- Q24. RETRIEVE TEACHERS WHO ARE DEPARTMENT HEADS
SELECT G.*
FROM GIAOVIEN G, BOMON B
WHERE G.MAGV = B.TRUONGBM

-- Q25. RETRIEVE THE FULL NAMES AND SALARIES OF TEACJER
SELECT G.HOTEN, G.LUONG
FROM GIAOVIEN G