-- LAB#7: TOPIC 7
-- NAME: PHÙNG QUỐC TUẤN
-- STUDENT'S ID: 19127616

USE QLDT;
GO

-- Q75
SELECT G.HOTEN, BM.TENBM
FROM GIAOVIEN G
LEFT JOIN BOMON BM ON G.MAGV = BM.TRUONGBM;

-- Q76
SELECT BM.TENBM, G.HOTEN
FROM BOMON BM
LEFT JOIN GIAOVIEN G ON BM.TRUONGBM = G.MAGV;

-- Q77
SELECT G.HOTEN, DT.TENDT
FROM GIAOVIEN G
LEFT JOIN DETAI DT ON G.MAGV = DT.GVCNDT;

-- Q78
DELETE FROM DETAI
WHERE MACD = 'NCPT';

-- Q79
SELECT MAGV, HOTEN,
       CASE WHEN LUONG < 1800 THEN N'THẤP'
              WHEN LUONG <= 2200 THEN N'TRUNG BÌNH'
              ELSE N'CAO' END AS N'MỨC LƯƠNG'
FROM GIAOVIEN;

-- Q80
SELECT G.MAGV, G.HOTEN, COUNT(DISTINCT G2.LUONG) + 1 AS N'XẾP HẠNG'
FROM GIAOVIEN G
LEFT JOIN GIAOVIEN G2 ON G2.LUONG > G.LUONG
GROUP BY G.MAGV, G.HOTEN;

-- Q81
SELECT G.MAGV, G.HOTEN, G.LUONG +
       CASE WHEN G.MAGV IN (SELECT TRUONGBM FROM BOMON) THEN 300 ELSE 0 END +
       CASE WHEN G.MAGV IN (SELECT TRUONGKHOA FROM KHOA) THEN 600 ELSE 0 END AS N'THU NHẬP'
FROM GIAOVIEN G;

-- Q82
SELECT MAGV, HOTEN, YEAR(NGSINH) +
       CASE WHEN PHAI = N'Nam' THEN 60 ELSE 55 END AS N'NĂM NGHỈ HƯU'
FROM GIAOVIEN;

-- Q83
SELECT G.MAGV, G.HOTEN, QL.HOTEN AS N'GIẢNG VIÊN QUẢN LÝ'
FROM GIAOVIEN G
LEFT JOIN GIAOVIEN QL ON G.GVQLCM = QL.MAGV;

-- Q84
SELECT BM.MABM, BM.TENBM, TBM.HOTEN AS N'TRƯỞNG BỘ MÔN', COUNT(G.MAGV) AS N'SỐ GIẢNG VIÊN'
FROM BOMON BM
LEFT JOIN GIAOVIEN TBM ON BM.TRUONGBM = TBM.MAGV
LEFT JOIN GIAOVIEN G ON BM.MABM = G.MABM
GROUP BY BM.MABM, BM.TENBM, TBM.HOTEN;

-- Q85
SELECT G.MAGV, G.HOTEN, CV.*
FROM GIAOVIEN G
JOIN THAMGIADT TG ON G.MAGV = TG.MAGV
JOIN CONGVIEC CV ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT
WHERE G.PHAI = N'Nam';

-- Q86
SELECT G.MAGV, G.HOTEN, CV.*
FROM GIAOVIEN G
LEFT JOIN THAMGIADT TG ON G.MAGV = TG.MAGV AND TG.MADT = '001'
LEFT JOIN CONGVIEC CV ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT;

-- Q87
SELECT G.MAGV, G.HOTEN, G.NGSINH, G.PHAI
FROM GIAOVIEN G
JOIN BOMON BM ON G.MAGV = BM.TRUONGBM
WHERE YEAR(G.NGSINH) + CASE WHEN G.PHAI = N'Nam' THEN 60 ELSE 55 END = 2014;

-- Q88
SELECT G.MAGV, G.HOTEN,
       YEAR(G.NGSINH) + CASE WHEN G.PHAI = N'Nam' THEN 60 ELSE 55 END AS N'NĂM NGHỈ HƯU'
FROM GIAOVIEN G
JOIN KHOA K ON G.MAGV = K.TRUONGKHOA;

-- Q89
CREATE TABLE DANHSACHTHIDUA (
    MAGV CHAR(3),
    SODTDAT INT,
    DANHHIEU NVARCHAR(40)
);

INSERT INTO DANHSACHTHIDUA (MAGV, SODTDAT)
SELECT G.MAGV, COUNT(DISTINCT TG.MADT)
FROM GIAOVIEN G
LEFT JOIN THAMGIADT TG ON G.MAGV = TG.MAGV AND TG.KETQUA = N'Đạt'
GROUP BY G.MAGV;

UPDATE DANHSACHTHIDUA
SET DANHHIEU = CASE WHEN SODTDAT = 0 THEN N'Không hoàn thành nhiệm vụ'
                    WHEN SODTDAT <= 2 THEN N'Hoàn thành nhiệm vụ'
                    WHEN SODTDAT <= 5 THEN N'Lao động tiên tiến'
                    ELSE N'Chiến sĩ thi đua' END;

-- Q90
SELECT G.MAGV, G.HOTEN,
       CASE WHEN G.LUONG < 1800 THEN N'THẤP' WHEN G.LUONG <= 2200 THEN N'TRUNG BÌNH' ELSE N'CAO' END AS N'MỨC LƯƠNG',
       AVG(G2.LUONG) AS N'LƯƠNG TB', MAX(G2.LUONG) AS N'LƯƠNG CAO NHẤT', MIN(G2.LUONG) AS N'LƯƠNG THẤP NHẤT'
FROM GIAOVIEN G
JOIN BOMON B ON G.MABM = B.MABM JOIN KHOA K ON B.MAKHOA = K.MAKHOA
JOIN GIAOVIEN G2 ON G2.PHAI = N'Nữ'
JOIN BOMON B2 ON G2.MABM = B2.MABM
JOIN KHOA K2 ON B2.MAKHOA = K2.MAKHOA
WHERE G.PHAI = N'Nữ' AND K.TENKHOA = N'Công nghệ thông tin'
GROUP BY G.MAGV, G.HOTEN, G.LUONG;

-- Q91
SELECT K.MAKHOA, K.TENKHOA, COUNT(G.MAGV) AS N'SỐ GIẢNG VIÊN'
FROM KHOA K
LEFT JOIN BOMON BM ON K.MAKHOA = BM.MAKHOA
LEFT JOIN GIAOVIEN G ON BM.MABM = G.MABM
GROUP BY K.MAKHOA, K.TENKHOA;

-- Q92
SELECT CD.MACD, CD.TENCD, SUM(DT.KINHPHI) AS N'KINH PHÍ CHỦ ĐỀ'
FROM CHUDE CD
LEFT JOIN DETAI DT ON CD.MACD = DT.MACD
GROUP BY CD.MACD, CD.TENCD WITH ROLLUP;

-- Q93
SELECT DT.MADT, DT.TENDT, DT.KINHPHI, SUM(D2.KINHPHI) AS N'TỔNG KINH PHÍ GVCN', AVG(D2.KINHPHI) AS N'KINH PHÍ TB GVCN'
FROM DETAI DT
JOIN DETAI D2 ON DT.GVCNDT = D2.GVCNDT
GROUP BY DT.MADT, DT.TENDT, DT.KINHPHI;

-- Q94
SELECT DT.MADT, DT.TENDT, DT.KINHPHI, SUM(D2.KINHPHI) AS N'TỔNG KINH PHÍ CẤP', AVG(D2.KINHPHI) AS N'KINH PHÍ TB CẤP'
FROM DETAI DT
JOIN DETAI D2 ON DT.CAPQL = D2.CAPQL
GROUP BY DT.MADT, DT.TENDT, DT.KINHPHI;

-- Q95
SELECT DT.CAPQL, DT.MACD, COUNT(*) AS N'SỐ ĐỀ TÀI'
FROM DETAI DT
GROUP BY DT.CAPQL, DT.MACD WITH CUBE;

-- Q96
SELECT BM.TENBM, G.PHAI, SUM(G.LUONG) AS N'TỔNG LƯƠNG'
FROM GIAOVIEN G
JOIN BOMON BM ON G.MABM = BM.MABM
GROUP BY BM.TENBM, G.PHAI WITH ROLLUP;

-- Q97
SELECT BM.TENBM, G.LUONG, COUNT(G.MAGV) AS N'SỐ GIẢNG VIÊN'
FROM GIAOVIEN G
JOIN BOMON BM ON G.MABM = BM.MABM JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Công nghệ thông tin'
GROUP BY BM.TENBM, G.LUONG WITH CUBE;


